#!/bin/bash

case "${1}" in
  configure)
    echo "Enabling & starting Sanity Check Timer Service"
    systemctl enable waggle-sanity-check.timer
    systemctl start waggle-sanity-check.timer || true
    ;;
esac
