#!/bin/bash

case "${1}" in
  configure)
    echo "Enabling & starting Sanity Check Service"
    systemctl enable waggle-sanity-check.service
    systemctl start waggle-sanity-check.service || true
    ;;
esac
